### ISSUE TITLE
Probable leak: $header_reader

### ISSUE THREAD

**Issue by undeference** [debug-ito/AnyEvent-Connector#2]
(Disclaimer: I don't use this module. I was just glancing at it and noticed a probable leak, but it's possible I overlooked something.)

https://github.com/debug-ito/AnyEvent-Connector/blob/11580a55433c74b6f727d37b0f0a38aba9bb500d/lib/AnyEvent/Connector/Proxy/http.pm#L47-L55
`$header_reader` is a circular reference and it doesn't look like anything is done to ensure it can be freed. It looks to me like you should `undef $header_reader` by subsequent `$cb->(…)`s.

**Comment by debug-ito** [comment]
Thanks for reporting! I'll look into it.

**Comment by debug-ito** [comment]
I just released AnyEvent-Connector-0.04. It fixes this issue, I think.
